FROM maven:3.9-amazoncorretto-25-alpine AS build

WORKDIR /app

COPY pom.xml ./pom.xml 
COPY src ./src

RUN mvn package

FROM amazoncorretto:25-alpine

WORKDIR /app

COPY --from=build /app/target/*.jar ./app.jar

CMD ["java", "-jar", "./app.jar"]
