name: "Ohana"

networks:
    # for creating & maintianing
    # the searchable web database
    infrastructure:

    # for handling the reception and
    # evaluation of, and response to,
    # user search queries
    userspace:

services:
    db:
        networks:
            - infrastructure
            - userspace
        build:
            context: ./services/db
            dockerfile: ./dockerfile
        container_name: ohana-db
        environment:
            PGUSER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_PORT: ${DB_CONTAINER_PORT}
        volumes:
            - db-data:/var/lib/ohana
        healthcheck:
            # Command for live tracking:
            # watch -n 1 'psql -d ohana -c "SELECT count(*) AS sites_count FROM sites; SELECT count(*) AS pages_count FROM pages; SELECT count(*) AS crawler_queue_count FROM crawler_queue; SELECT count(*) AS indexer_queue_count FROM indexer_queue; SELECT count(*) AS ranker_queue_count FROM ranking_engine_queue;"'
            test: ["CMD", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5

    # backup:
    #     image: postgres:18.4-alpine
    #     container_name: ohana-db-backup

    crawler:
        networks:
            - infrastructure
        build:
            context: ./services/crawler
            dockerfile: ./build/dockerfile
        container_name: ohana-crawler
        depends_on:
            db:
                condition: service_healthy
        env_file:
            - ./.env

    indexer:
        networks:
            - infrastructure
        build:
            context: ./services/indexer
            dockerfile: ./dockerfile
        container_name: ohana-indexer
        depends_on:
            db:
                condition: service_healthy
        env_file:
            - ./.env

    ranking_engine:
        networks:
            - infrastructure
        build:
            context: ./services/ranking_engine
            dockerfile: ./dockerfile
        container_name: ohana-ranking_engine
        depends_on:
            db:
                condition: service_healthy

    query_engine:
        networks:
            - "userspace"
        build:
            context: ./services/query_engine
            dockerfile: ./dockerfile
        container_name: ohana-query_engine
        depends_on:
            db:
                condition: service_healthy

    client:
        container_name: ohana-client
        networks:
            - userspace
        build:
            context: ./services/client
            dockerfile: ./dockerfile
        volumes:
            - client-public:/var/www/html/public
        healthcheck:
            test: ["CMD-SHELL", "php-fpm -t"]
            interval: 5s
            timeout: 3s
            retries: 10
        depends_on:
            db:
                condition: service_healthy

    server:
        container_name: ohana-server
        image: nginx:stable-alpine-slim
        networks:
            - userspace
        depends_on:
            client:
                condition: service_healthy
        volumes:
            - client-public:/var/www/html/public:ro
            - ./services/server/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "3020:80"

volumes:
    db-data:
    client-public:
