name: "Ohana"

networks:
    # for creating & maintianing
    # the searchable web database
    infrastructure:

    # for handling the reception and
    # evaluation of, and response to,
    # user search queries
    userspace:

services:
    db:
        networks:
            - infrastructure
            - userspace
        build:
            context: ./services/db
            dockerfile: ./dockerfile
        container_name: ohana-db
        environment:
            PGUSER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_PORT: ${DB_CONTAINER_PORT}
        volumes:
            - db-data:/var/lib/ohana
        healthcheck:
            test: ["CMD", "pg_isready"]
            interval: 1s
            timeout: 5s
            retries: 100

    # backup:
    #     image: postgres:18.4-alpine
    #     container_name: ohana-db-backup

    db-init:
        networks:
            - infrastructure
        build:
            context: ./services
            dockerfile: ./db-init/build/dockerfile
        container_name: ohana-db_initializer
        depends_on:
            db:
                condition: service_healthy
        env_file:
            - ./.env

    crawler:
        networks:
            - infrastructure
        build:
            context: ./services
            dockerfile: ./crawler/build/dockerfile
        container_name: ohana-crawler
        depends_on:
            db-init:
                condition: service_completed_successfully
        env_file:
            - ./.env

    indexer:
        networks:
            - infrastructure
        build:
            context: ./services/indexer
            dockerfile: ./dockerfile
        container_name: ohana-indexer
        depends_on:
            db-init:
                condition: service_completed_successfully
        env_file:
            - ./.env
        volumes:
            - index-data:/data/lucene-index

    ranking-engine:
        networks:
            - infrastructure
        build:
            context: ./services/ranking-engine
            dockerfile: ./dockerfile
        container_name: ohana-ranking-engine
        depends_on:
            db-init:
                condition: service_completed_successfully

    query-engine:
        networks:
            - "userspace"
        build:
            context: ./services/query-engine
            dockerfile: ./dockerfile
        container_name: ohana-query-engine
        volumes:
            - index-data:/data/lucene-index
        env_file:
            - ./.env
        depends_on:
            db-init:
                condition: service_completed_successfully

    client:
        container_name: ohana-client
        networks:
            - userspace
        build:
            context: ./services/client
            dockerfile: ./dockerfile
        volumes:
            - ./services/client/public:/var/www/html/public
        healthcheck:
            test: ["CMD-SHELL", "php-fpm -t"]
            interval: 5s
            timeout: 3s
            retries: 10

    server:
        container_name: ohana-server
        image: nginx:stable-alpine-slim
        networks:
            - userspace
        depends_on:
            client:
                condition: service_healthy
        volumes:
            - ./services/client/public:/var/www/html/public:ro
            - ./services/server/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "3020:80"

volumes:
    db-data:
    index-data:
