-- +goose Up
DROP TABLE "Pages";

CREATE TABLE IF NOT EXISTS "pages" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "site_id" INTEGER NOT NULL,
    "title" TEXT,
    "description" TEXT,
    "data" JSONB NOT NULL UNIQUE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "sites" (
    "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "second_and_top_level_domain" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

ALTER TABLE "pages"
ADD FOREIGN KEY ("site_id") REFERENCES "sites" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- +goose Down
DROP TABLE "pages";

DROP TABLE "sites";