<?php

final class Language
{
    public function __construct(
        public string $ISOcode,
        public string $Name,
        public string $Emoji
    ) {
    }
}

$LanguageNames = [
    'aa' => 'Afar',
    'ab' => 'Abkhazian',
    'af' => 'Afrikaans',
    'ak' => 'Akan',
    'am' => 'Amharic',
    'ar' => 'Arabic',
    'az' => 'Azerbaijani',
    'be' => 'Belarusian',
    'bg' => 'Bulgarian',
    'bn' => 'Bengali',
    'br' => 'Breton',
    'bs' => 'Bosnian',
    'ca' => 'Catalan',
    'co' => 'Corsican',
    'cs' => 'Czech',
    'cy' => 'Welsh',
    'da' => 'Danish',
    'de' => 'German',
    'dv' => 'Divehi',
    'dz' => 'Dzongkha',
    'el' => 'Greek',
    'en' => 'English',
    'eo' => 'Esperanto',
    'es' => 'Spanish',
    'et' => 'Estonian',
    'eu' => 'Basque',
    'fa' => 'Persian',
    'fi' => 'Finnish',
    'fj' => 'Fijian',
    'fr' => 'French',
    'fy' => 'Western Frisian',
    'ga' => 'Irish',
    'gd' => 'Scottish Gaelic',
    'gl' => 'Galician',
    'gu' => 'Gujarati',
    'ha' => 'Hausa',
    'he' => 'Hebrew',
    'hi' => 'Hindi',
    'hr' => 'Croatian',
    'hu' => 'Hungarian',
    'hy' => 'Armenian',
    'id' => 'Indonesian',
    'ig' => 'Igbo',
    'is' => 'Icelandic',
    'it' => 'Italian',
    'ja' => 'Japanese',
    'jv' => 'Javanese',
    'ka' => 'Georgian',
    'km' => 'Khmer',
    'kn' => 'Kannada',
    'ko' => 'Korean',
    'ku' => 'Kurdish',
    'ky' => 'Kyrgyz',
    'la' => 'Latin',
    'lb' => 'Luxembourgish',
    'ln' => 'Lingala',
    'lo' => 'Lao',
    'lt' => 'Lithuanian',
    'lv' => 'Latvian',
    'mg' => 'Malagasy',
    'mi' => 'Māori',
    'mk' => 'Macedonian',
    'ml' => 'Malayalam',
    'mn' => 'Mongolian',
    'mr' => 'Marathi',
    'ms' => 'Malay',
    'mt' => 'Maltese',
    'my' => 'Burmese',
    'ne' => 'Nepali',
    'nl' => 'Dutch',
    'no' => 'Norwegian',
    'ny' => 'Chichewa',
    'oc' => 'Occitan',
    'pa' => 'Punjabi',
    'pl' => 'Polish',
    'ps' => 'Pashto',
    'pt' => 'Portuguese',
    'ro' => 'Romanian',
    'ru' => 'Russian',
    'rw' => 'Kinyarwanda',
    'sd' => 'Sindhi',
    'si' => 'Sinhala',
    'sk' => 'Slovak',
    'sl' => 'Slovenian',
    'sm' => 'Samoan',
    'so' => 'Somali',
    'sq' => 'Albanian',
    'sr' => 'Serbian',
    'ss' => 'Swati',
    'st' => 'Southern Sotho',
    'su' => 'Sundanese',
    'sv' => 'Swedish',
    'sw' => 'Swahili',
    'ta' => 'Tamil',
    'te' => 'Telugu',
    'th' => 'Thai',
    'tl' => 'Tagalog',
    'tn' => 'Tswana',
    'to' => 'Tongan',
    'tr' => 'Turkish',
    'ts' => 'Tsonga',
    'uk' => 'Ukrainian',
    'ur' => 'Urdu',
    'uz' => 'Uzbek',
    'vi' => 'Vietnamese',
    'wo' => 'Wolof',
    'xh' => 'Xhosa',
    'yo' => 'Yoruba',
    'zh' => 'Chinese',
    'zu' => 'Zulu',

    'un' => 'Uninspected',
    'xx' => 'Unknown'
];

$LanguageEmojis = [
    'aa' => '🇩🇯',
    'ab' => '🇬🇪',
    'af' => '🇿🇦',
    'ak' => '🇬🇭',
    'am' => '🇪🇹',
    'ar' => '🇸🇦',
    'az' => '🇦🇿',
    'be' => '🇧🇾',
    'bg' => '🇧🇬',
    'bn' => '🇧🇩',
    'br' => '🇫🇷',
    'bs' => '🇧🇦',
    'ca' => '🇪🇸',
    'co' => '🇫🇷',
    'cs' => '🇨🇿',
    'cy' => '🏴',
    'da' => '🇩🇰',
    'de' => '🇩🇪',
    'dv' => '🇲🇻',
    'dz' => '🇧🇹',
    'el' => '🇬🇷',
    'en' => '🇬🇧',
    'eo' => '🌐',
    'es' => '🇪🇸',
    'et' => '🇪🇪',
    'eu' => '🇪🇸',
    'fa' => '🇮🇷',
    'fi' => '🇫🇮',
    'fj' => '🇫🇯',
    'fr' => '🇫🇷',
    'fy' => '🇳🇱',
    'ga' => '🇮🇪',
    'gd' => '🏴',
    'gl' => '🇪🇸',
    'gu' => '🇮🇳',
    'ha' => '🇳🇬',
    'he' => '🇮🇱',
    'hi' => '🇮🇳',
    'hr' => '🇭🇷',
    'hu' => '🇭🇺',
    'hy' => '🇦🇲',
    'id' => '🇮🇩',
    'ig' => '🇳🇬',
    'is' => '🇮🇸',
    'it' => '🇮🇹',
    'ja' => '🇯🇵',
    'jv' => '🇮🇩',
    'ka' => '🇬🇪',
    'km' => '🇰🇭',
    'kn' => '🇮🇳',
    'ko' => '🇰🇷',
    'ku' => '🇮🇶',
    'ky' => '🇰🇬',
    'la' => '🇻🇦',
    'lb' => '🇱🇺',
    'ln' => '🇨🇩',
    'lo' => '🇱🇦',
    'lt' => '🇱🇹',
    'lv' => '🇱🇻',
    'mg' => '🇲🇬',
    'mi' => '🇳🇿',
    'mk' => '🇲🇰',
    'ml' => '🇮🇳',
    'mn' => '🇲🇳',
    'mr' => '🇮🇳',
    'ms' => '🇲🇾',
    'mt' => '🇲🇹',
    'my' => '🇲🇲',
    'ne' => '🇳🇵',
    'nl' => '🇳🇱',
    'no' => '🇳🇴',
    'ny' => '🇲🇼',
    'oc' => '🇫🇷',
    'pa' => '🇮🇳',
    'pl' => '🇵🇱',
    'ps' => '🇦🇫',
    'pt' => '🇵🇹',
    'ro' => '🇷🇴',
    'ru' => '🇷🇺',
    'rw' => '🇷🇼',
    'sd' => '🇵🇰',
    'si' => '🇱🇰',
    'sk' => '🇸🇰',
    'sl' => '🇸🇮',
    'sm' => '🇼🇸',
    'so' => '🇸🇴',
    'sq' => '🇦🇱',
    'sr' => '🇷🇸',
    'ss' => '🇸🇿',
    'st' => '🇱🇸',
    'su' => '🇮🇩',
    'sv' => '🇸🇪',
    'sw' => '🇹🇿',
    'ta' => '🇮🇳',
    'te' => '🇮🇳',
    'th' => '🇹🇭',
    'tl' => '🇵🇭',
    'tn' => '🇧🇼',
    'to' => '🇹🇴',
    'tr' => '🇹🇷',
    'ts' => '🇿🇦',
    'uk' => '🇺🇦',
    'ur' => '🇵🇰',
    'uz' => '🇺🇿',
    'vi' => '🇻🇳',
    'wo' => '🇸🇳',
    'xh' => '🇿🇦',
    'yo' => '🇳🇬',
    'zh' => '🇨🇳',
    'zu' => '🇿🇦',

    'un' => '🏳️',
    'xx' => '🏴'
];

$Languages = [];

foreach ($LanguageNames as $ISOcode => $name) {
    if (!isset($LanguageEmojis[$ISOcode])) {
        throw new RuntimeException(
            "Missing emoji for language code: {$ISOcode}"
        );
    }

    $Languages[$ISOcode] = new Language(
        ISOcode: $ISOcode,
        Name: $name,
        Emoji: $LanguageEmojis[$ISOcode]
    );
}

// return $Languages;
