-- +goose Up
CREATE TABLE IF NOT EXISTS "domain_blacklist" (
    "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "domain" TEXT NOT NULL,
    PRIMARY KEY ("id")
);

-- +goose Down
DROP TABLE "domain_blacklist";