FROM amazoncorretto:26-alpine AS build

WORKDIR /app

COPY src ./src

RUN mkdir -p /out \
    && find /app/src -type f -print \
    && javac -d /out /app/src/ranking_engine/src/RankingEngine.java

FROM amazoncorretto:26-alpine AS runtime

WORKDIR /app

COPY --from=build /out/ ./

CMD ["java", "-cp", "/app", "ranking_engine.src.RankingEngine"]
