FROM gradle:9.8.0-jdk25-alpine AS build

WORKDIR /repo

COPY . .

RUN gradle check

RUN gradle clean

RUN gradle jar

FROM amazoncorretto:25-alpine AS dist

WORKDIR /app

COPY --from=build /repo/app/build/libs/app.jar ./app.jar

CMD ["java", "-jar", "/app/app.jar"]
