ARG APP_NAME=ohana-query_engine

FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine AS build

WORKDIR /app

# COPY Cargo.toml Cargo.lock ./
# COPY src ./

# RUN cargo build --release

FROM mcr.microsoft.com/dotnet/runtime:10.0-alpine AS dist

# COPY --from=build /app/target/release/query_engine /bin/query_engine

# CMD ["/bin/query_engine"]