FROM postgres:18-alpine

ARG PGVECTOR_VERSION=0.8.6

RUN apk add --no-cache --virtual .build-deps \
        alpine-sdk \
        git \
        clang21 \
        llvm21 \
    && git clone --branch "v${PGVECTOR_VERSION}" --depth 1 \
        https://github.com/pgvector/pgvector.git /tmp/pgvector \
    && cd /tmp/pgvector \
    && make PG_CONFIG=/usr/local/bin/pg_config \
    && make PG_CONFIG=/usr/local/bin/pg_config install \
    && rm -rf /tmp/pgvector \
    && apk del .build-deps

EXPOSE 5432

RUN cat > /usr/local/bin/monitor <<'EOF'
#!/bin/sh

exec watch -n 1 '
psql -d ohana -c "
SELECT count(*) AS sites_count FROM sites;
SELECT count(*) AS pages_count FROM pages;
SELECT count(*) AS crawler_queue_count FROM crawler_queue;
SELECT count(*) AS indexer_queue_count FROM indexer_queue;
SELECT count(*) AS ranker_queue_count FROM ranking_engine_queue;
"
'
EOF

RUN chmod +x /usr/local/bin/monitor

CMD ["postgres"]
